 " Basic Settings
inoremap jk <Esc>
set noswapfile
set clipboard=unnamed
set cursorline
set hlsearch
set backspace=indent,eol,start
set number

" Use spaces, not tabs
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Airline
let g:airline_theme='term'
let g:airline_extensions=[]
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'default'

" Ale Linting
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0

" Color Scheme
color brogrammer

" NERDTREE
" Remap Keys
map <C-n> :NERDTreeToggle<CR>
map <C-b> :NERDTreeToggle<CR>
" Show hidden files
let NERDTreeShowHidden=1


" Plug Package Manager
call plug#begin('~/.vim/plugged')

" NerdTree
Plug 'scrooloose/nerdtree'

" Vim Airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Language Plugins
Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript'
Plug 'leshill/vim-json'
Plug 'milch/vim-fastlane'
Plug 'leafgarland/typescript-vim'

" Linting
Plug 'w0rp/ale'

" Blogging Plugins
Plug 'reedes/vim-pencil'


call plug#end()
" End Plugin Manager
