"  Remap ESC key to "jk"
inoremap jk <Esc>

"  Do not use a swapfile when editing
set noswapfile

"  TODO: Not sure what this does
set clipboard=unnamed

"  Create a line under the cursor
"  set cursorline

"  Highlight search
set hlsearch

"  Fix backspacing in vim
set backspace=indent,eol,start

"  Show line numbers
"  set number

"  Spaces instead of tabs
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set expandtab

" Set print width to 80
au BufRead,BufNewFile *.md setlocal textwidth=80
au BufRead,BufNewFile *.mdx setlocal textwidth=80
au BufRead,BufNewFile *.txt setlocal textwidth=80

" Turn on spellchecker
au BufRead,BufNEwFile *.md setlocal spell spelllang=en_us
au BufRead,BufNEwFile *.mdx setlocal spell spelllang=en_us
au BufRead,BufNEwFile *.txt setlocal spell spelllang=en_us

" Airline
let g:airline_theme='term'
let g:airline_extensions=[]
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'default'

" Color Scheme
color brogrammer

" Plug Package Manager
call plug#begin('~/.vim/plugged')

" Vim Airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()
" End Plugin Manager
