export DOTFILES=$HOME/.dotfiles

# Add GNU Utils to Path
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

ZSH_MODULES=$DOTFILES/zsh/modules

# Prompt
source $DOTFILES/zsh/prompt/spaceship.zsh

# Git completions
source $DOTFILES/zsh/completions/completions.zsh

# ZSH Modules
source $ZSH_MODULES/aliases.zsh
source $ZSH_MODULES/nvm.zsh
source $ZSH_MODULES/colors.zsh
source $ZSH_MODULES/android.zsh
source $ZSH_MODULES/functions.zsh
source $ZSH_MODULES/secrets.zsh


# !! IMPORTANT !!
# When NVM installs it will automatically
# Add a command to init it here
# DO NOT COMMIT THIS CODE
# It is done via nvm.zsh
